# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scgsim',
                'doc_host': 'https://changebio.github.io',
                'git_url': 'https://github.com/changebio/scgsim',
                'lib_path': 'scgsim'},
  'syms': {'scgsim.core': {'scgsim.core.foo': ('core.html#foo', 'scgsim/core.py')}}}
